MovieStore.MVC/Views/Shared/Components/Genres/GenresViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieStore.Core.ServiceInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieStore.MVC.Views.Shared.Components.Genres
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly IGenreService _genreService;

        public GenresViewComponent(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var genres = await _genreService.GetAllGenres();
            return View(genres);
        }

    }
}

MovieStore.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieStore.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Top Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown">Genres</a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                @await Component.InvokeAsync("Genres")
                            </div>
                        </li>
                        <partial name="_LoginResult"/>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() 
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MovieStore.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MovieStore.MVC/Views/Shared/_LoginResult.cshtml
@*//Check if the user is Authented and if yes, then show the first name and last name, else show login and signup buttons*@
@if (User.Identity.IsAuthenticated)
{
    <li ngbDropdown class="nav-item dropdown text-capitalize">
        <a class="nav-link dropdown-toggle" id="dropdown01" data-toggle="dropdown"
           style="cursor: pointer;" aria-haspopup="true"
           aria-expanded="false">
            @User.Claims.FirstOrDefault(c=>c.Type==System.Security.Claims.ClaimTypes.GivenName).Value
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item">Library (myMoviesCount)</a>
            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out</a>
            <a class="dropdown-item">My Account</a>
        </div>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Sign Up</a>
    </li>
}

MovieStore.MVC/Views/Shared/_MovieCard.cshtml
@model MovieStore.Core.Entities.Movie
<div class="col-6 cl-lg-3 col-sm-4 col-xl-2">
    <a>
        <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title" />
    </a>
</div>